#!/usr/bin/perl

# Copyright 2016 Koha-Suomi
#

use Modern::Perl;
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use utf8;
use Carp;
use Getopt::Long qw(:config no_ignore_case);
use POSIX();
use Data::Dumper;

use OLED::Server;

my %params = ();

GetOptions(
    'h|help'                      => \$params{help},
    'v|verbose:i'                 => \$params{Verbose},
    'c:s'                         => \$params{configFile},
);

my $usage = <<USAGE;

An OLED display server managing OLED displays over SPI

  -h --help
  -v --verbose
  -c             config file

USAGE

if ($params{help}) {
  print $usage;
  exit 0;
}


my $oled = OLED::Server::start_daemon(\%params);
